### ISSUE TITLE
Issue loading Arcgis basemap layer and reference layer.

### ISSUE THREAD

**Issue by bijoyvalsan** [Esri/esri-leaflet-vector#40] opened 2018-02-15 12:56 UTC
Hi,

I am trying to load ArcGis light gray base map (with out label - vector) and the reference layer (labels -vector). when i add initially it loads fine. as i move on the map the labels disappear.
below it the code i am using. kindly help

       var map = L.map('map').setView([0, 0], 2);       
        var baselayer = L.esri.Vector.layer('291da5eab3a0412593b66d384379f89f');
        var referencelayer = L.esri.Vector.layer('1768e8369a214dfab4e2167d5c5f2454');
        map.addLayer(baselayer);
        map.addLayer(referencelayer);

**Comment by gavinr** [comment] 2018-02-15 14:18
It looks like if you only load one at a time, it works ok:
https://jsbin.com/civoxoh/edit?html,output

So based on that, I think this is a duplicate of #38.

**Comment by jgravois** [comment] 2018-02-15 17:28
> this is a duplicate of #38

agreed.

**Closed by jgravois** 2018-02-15 17:28 UTC
