### ISSUE TITLE
Incorrect CSS Color Prevents arcgis/navigation maps from loading

### ISSUE THREAD

**Issue by sheeley820** [Esri/esri-leaflet-vector#212] opened 2023-11-16 20:54 UTC
### Describe the bug

I know this bug is not directly in the domain of `esri-leaflet-vector`, however, switching to the V2 api for styles is what has brought this issue to the forefront.

I have not been able to determine when this bug was introduced, but can confirm that it exists in the latest version of MapLibreGL.

In the "Water point/Dam or weir" property of the arcgis/navigation map Styles (https://basemapstyles-api.arcgis.com/arcgis/rest/services/styles/v2/styles/arcgis/navigation) the paint.text-halo-color is set to #fffffr, which is an invalid hexadecimal color.

An example can be seen [here](https://developers.arcgis.com/esri-leaflet/samples/switching-basemaps/) by selecting the "arcgis/navigation" layer. In the console you will see the following error:
```javascript
Error: layers[142].paint.text-halo-color: color expected, "#fffffr" found
```

maplibre-gl-js version: 3.3.1

browser: All

Expected Behavior
The map should load without an error.

Actual Behavior
The map does not load.

### Reproduction

1. Load the arcgis/navigation map layer
2. See the map not load

Link to Demonstration
https://developers.arcgis.com/esri-leaflet/samples/switching-basemaps/

### Logs

```shell
Error: layers[142].paint.text-halo-color: color expected, "#fffffr" found
```

### System Info

```shell
Leaflet Version: 1.5.0
maplibre-gl-js version: 3.3.1
esri-leaflet-vector version: 4.2.2
```

**Comment by gavinr-maps** [comment] 2023-11-17 02:57
Hi @sheeley820. Thanks for reporting this.

I agree with you that `#fffffr` seems like an invalid HTML color code.

The associated ArcGIS Online item for that basemap is https://www.arcgis.com/home/item.html?id=63c47b7177f946b49902c24129b87252 (if you click the `View Style` button you'll see the same invalid HTML code `#fffffr`), so I think one step you can take is to leave a comment on that item reporting your finding. I will also try to find out if there is a better place for you to report this issue. 

Thanks!

**Comment by gavinr-maps** [comment] 2023-11-17 03:00
If you click into the author of that ArcGIS Online item, https://www.arcgis.com/home/user.html?user=esri_vector , you'll see an email address provided there. So in addition to the above instructions, I would ask you to please send a note to that email address.

**Comment by gowin20** [comment] 2023-11-17 19:08
@sheeley820 @gavinr-maps I have reached out to the proper internal teams at Esri and they are working to resolve this. Hopefully it gets fixed soon.

The problem is related to the data for the `arcgis/navigation` layer, which does not currently work in any library. Not leaflet-specific

**Comment by sheeley820** [comment] 2023-11-17 19:24
@gowin20 Yes, agreed.  However, I knew that the maintainers of this repo work at Esri and are fairly active, and finding a good way to contact Esri through their website was not very successful.  Also, it provides visibility for other users who may be seeing the same issue.

I have reached out to Andy Green at Esri and he has informed me that they plan on releasing a fix on November 29'th.  Once that fix is released I will close this issue.

Thanks to Gavin for pointing me to the right contact.

**Comment by patrickarlt** [comment] 2023-12-01 16:54
Looks like they have released a fix so I am closing this.

**Closed by patrickarlt** 2023-12-01 16:54 UTC
